spring:
  jpa: 
    database: POSTGRESQL
    open-in-view: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://music-app-db:5432/postgres
    username: postgres
    password: postgres