version: '3.8'

volumes:
  data:


services:
  backend:
    container_name: music-distribution-backend
    image: mcr.microsoft.com/devcontainers/java:1-17-bullseye
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ..:/workspaces/backend:cached
      - ~/.ssh:/workspaces/.ssh
    command: sleep infinity
    depends_on:
      - db

  db:
    container_name: music-distribution-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../db/initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres